CREATE TABLE CURSO(
    ID INTEGER AUTO_INCREMENT,
    NOME VARCHAR(100),
    PRIMARY KEY(ID)
);

CREATE TABLE PROFESSOR(
    ID INTEGER AUTO_INCREMENT,
    NOME VARCHAR(100),
    PRIMARY KEY(ID)
);

CREATE TABLE TURMA(
    ID INTEGER AUTO_INCREMENT,
    ID_CURSO INTEGER NOT NULL,
    ID_PROFESSOR INTEGER NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_CURSO
    FOREIGN KEY(ID_CURSO)
    REFERENCES CURSO(ID),
    CONSTRAINT FK_PROFESSOR
    FOREIGN KEY(ID_PROFESSOR)
    REFERENCES PROFESSOR(ID)
);

CREATE TABLE ALUNO(
    ID INTEGER AUTO_INCREMENT,
    NOME VARCHAR(100),
    EMAIL VARCHAR(100),
    ID_TURMA INT NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_TURMA
    FOREIGN KEY (ID_TURMA)
    REFERENCES TURMA(ID)
);