CREATE TABLE CURSO(
    ID SERIAL UNIQUE,
    NOME VARCHAR,
    PRIMARY KEY(ID)
)

CREATE TABLE PROFESSOR(
    ID SERIAL UNIQUE,
    NOME VARCHAR
    PRIMARY KEY(ID)
)

CRATE TABLE TURMA(
    ID SERIAL UNIQUE,
    ID_CURSO INTEGER,
    ID_PROFESSOR INTEGER,
    PRIMARY KEY(ID),
    CONSTRAINT FK_CURSO
    FOREIGN KEY(ID_CURSO)
    REFERENCES CURSO(ID),
    CONSTRAINT FK_PROFESSOR
    FOREIGN KEY(ID_PROFESSOR)
    REFERENCES PROFESSOR(ID) 
)

CREATE TABLE ALUNO(
    ID SERIAL UNIQUE,
    NOME VARCHAR,
    EMAIL VARCHAR,
    ID_TURMA INTEGER,
    PRIMARY KEY(ID),
    CONSTRAINT FK_TURMA
    FOREIGN KEY (ID_TURMA)
    REFERENCES TURMA(ID)
)